version: "3.8"

services:
  postgres-line-provider:
    image: postgres:16
    container_name: postgres-line-provider
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-bet-maker:
    image: postgres:16
    container_name: postgres-bet-maker
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  line-provider:
    build: ./line-provider
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-line-provider:
        condition: service_started

  bet-maker:
    build: ./bet-maker
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-bet-maker:
        condition: service_started


volumes:
  postgres_data:
